[package]
name = "ledge-ai-feed"
version = "0.1.0"
edition = "2021"

[dependencies]
rss = "2.0"
chrono = "0.4"
scraper = "0.21"
pulldown-cmark = "0.13"
serde_json = "1.0"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1.0", features = ["full"] }
